export default [
  {
    path: '/company/dashboard',
    name: 'ENT-DASH-02',
    component: () => import('../views/ent/Dashboard.vue'),
    meta: { title: '企业工作台', menu: '工作台' },
  },
  {
    path: '/company/admin',
    name: 'ENT-ROLE-ADMIN',
    component: () => import('../views/ent/AdminHome.vue'),
    meta: { title: '企业管理员工作台', menu: '企业管理员' },
  },
  {
    path: '/company/admin/accounts',
    name: 'ENT-ADMIN-ACCOUNTS',
    component: () => import('../views/ent/CompanyAccountManage.vue'),
    meta: { title: '人员账号管理', menu: '人员账号' },
  },
  {
    path: '/company/recruiter',
    name: 'ENT-ROLE-RECRUITER',
    component: () => import('../views/ent/RecruiterHome.vue'),
    meta: { title: '招聘负责人工作台', menu: '招聘负责人' },
  },
  {
    path: '/company/contact',
    name: 'ENT-ROLE-CONTACT',
    component: () => import('../views/ent/ContactHome.vue'),
    meta: { title: '企业联系人工作台', menu: '企业联系人' },
  },
  {
    path: '/company/mentor',
    name: 'ENT-ROLE-MENTOR',
    component: () => import('../views/ent/MentorHome.vue'),
    meta: { title: '企业导师工作台', menu: '企业导师' },
  },
  {
    path: '/company/register',
    name: 'ENT-REG-01',
    component: () => import('../views/ent/RegisterWizard.vue'),
    meta: { title: '企业注册向导' },
  },
  {
    path: '/company/jobs',
    name: 'ENT-JOB-01',
    component: () => import('../views/ent/JobList.vue'),
    meta: { title: '实习需求管理', menu: '实习需求' },
  },
  {
    path: '/company/jobs/new',
    name: 'ENT-JOB-02',
    component: () => import('../views/ent/JobEdit.vue'),
    meta: { title: '新建实习需求' },
  },
  {
    path: '/company/applications',
    name: 'ENT-APP-01',
    component: () => import('../views/ent/ApplicationList.vue'),
    meta: { title: '学生申请管理', menu: '学生申请' },
  },
  {
    path: '/company/internships',
    name: 'ENT-INTRN-01',
    component: () => import('../views/ent/InternshipList.vue'),
    meta: { title: '实习对接管理', menu: '实习对接' },
  },
  {
    path: '/company/internships/:id/evaluation',
    name: 'ENT-EVAL-01',
    component: () => import('../views/ent/Evaluation.vue'),
    meta: { title: '实习评价' },
  },
  {
    path: '/company/mentors',
    name: 'ENT-MENTOR-01',
    component: () => import('../views/ent/MentorManage.vue'),
    meta: { title: '企业指导老师', menu: '指导老师' },
  },
  {
    path: '/company/profile',
    name: 'ENT-PROF-01',
    component: () => import('../views/ent/Profile.vue'),
    meta: { title: '企业信息管理', menu: '企业信息' },
  },
  {
    path: '/company/process',
    name: 'ENT-PROC-01',
    component: () => import('../views/ent/Process.vue'),
    meta: { title: '流程总览' },
  },
  {
    path: '/company/notifications',
    name: 'ENT-NOTI-01',
    component: () => import('../views/ent/Notifications.vue'),
    // TODO: 待确认 — 企业通知页面 ID 未在资产台账中确认
    meta: { title: '通知公告' },
  },
  {
    path: '/company/mentors/list',
    name: 'ENT-MENT-01',
    component: () => import('../views/ent/MentorList.vue'),
    meta: { title: '企业指导老师列表' },
  },
  {
    path: '/portal',
    name: 'PortalLanding',
    component: () => import('../views/ent/PortalLanding.vue'),
    meta: { title: '企业门户' },
  },
  {
    path: '/portal/console',
    name: 'PortalConsole',
    component: () => import('../views/ent/PortalConsole.vue'),
    meta: { title: '企业管理控制台' },
  },
]
